{% set data = load_setup_py_data() %}


package:
  name: pie-chart-js
  version: {{ data.version }}


source:
  - path: ../


build:
  include_recipe: True


requirements:
  build:
    - setuptools
    - python

  run:
    - python

test:
  imports:
    - pie_chart

about:
  home: {{ data.url }}
  license: MIT
  license_file: LICENSE.md
  license_family: MIT

  summary: {{ data.description }}
  description: {{ data.long_description }}
  doc_url: http://docs.3steps.cn
  dev_url: {{ data.url }}